feat: noscript support
vueuse/head pull request #71
Opened 2022-06-09 20:58 UTC by vis97c

Formatting changes obey to prettier.

2022-07-23 11:40 UTC, ricardogobbosouza commented
@antfu Any idea when it will be merged?

2022-07-23 19:17 UTC, antfu requested changes
Please revert the format changes, thanks.

2022-07-23 19:38 UTC, vis97c commented
> Please revert the format changes, thanks.

Done

2022-07-24 05:52 UTC, antfu approved these changes

2022-07-24 05:52 UTC, merged